<?php
/**
 * Live Google reviews for inthelightroofing.com, from the Places API (New).
 *
 * GENERATED by build/reviews-live.mjs on every publish. Do not edit this file --
 * edit reviewsPhp() there and republish. Setup and cost notes are in that file.
 */

ini_set('display_errors', '0');
error_reporting(E_ALL);

header('Content-Type: application/json; charset=utf-8');
header('X-Robots-Tag: noindex');
header('X-Content-Type-Options: nosniff');

const ITLR_TTL = 21600;           // a cached answer is fresh for six hours
const ITLR_RETRY = 900;           // after a failed call, fifteen minutes before the next
const ITLR_MAX_STALE = 2592000;   // a stale answer is served for thirty days at most
const ITLR_QUERY = 'In The Light Roofing, 871 N Fenwick St, Allentown, PA 18109';

function itlr_out($payload, $maxAge)
{
    header('Cache-Control: public, max-age=' . (int) $maxAge);
    echo json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    exit;
}

if (!in_array(isset($_SERVER['REQUEST_METHOD']) ? $_SERVER['REQUEST_METHOD'] : 'GET', ['GET', 'HEAD'], true)) {
    http_response_code(405);
    itlr_out(['ok' => false, 'reason' => 'method'], 0);
}

/** The folder beside public_html, which the web server does not serve. */
function itlr_private_dir()
{
    $root = !empty($_SERVER['DOCUMENT_ROOT']) ? rtrim($_SERVER['DOCUMENT_ROOT'], '/') : dirname(__DIR__);
    return dirname($root) . '/itlr-private';
}

function itlr_config()
{
    $key = (string) getenv('ITLR_GOOGLE_PLACES_KEY');
    $place = (string) getenv('ITLR_GOOGLE_PLACE_ID');
    $file = itlr_private_dir() . '/google-places.php';
    if (is_file($file)) {
        $c = include $file;
        if (is_array($c)) {
            if (!empty($c['key'])) {
                $key = (string) $c['key'];
            }
            if (!empty($c['place_id'])) {
                $place = (string) $c['place_id'];
            }
        }
    }
    return ['key' => trim($key), 'place_id' => trim($place)];
}

/** A writable cache folder outside the web root, or null. */
function itlr_cache_dir()
{
    foreach ([itlr_private_dir() . '/cache', rtrim(sys_get_temp_dir(), '/') . '/itlr-reviews'] as $d) {
        if ((is_dir($d) || @mkdir($d, 0700, true)) && is_writable($d)) {
            return $d;
        }
    }
    return null;
}

/** One call to Google. Returns the decoded body, or null and a line in the error log. */
function itlr_http($method, $path, $key, $fieldMask, $body = null)
{
    $base = getenv('ITLR_PLACES_BASE') ?: 'https://places.googleapis.com/v1';
    $url = $base . $path;
    $headers = ['X-Goog-Api-Key: ' . $key, 'X-Goog-FieldMask: ' . $fieldMask, 'Accept: application/json'];
    if ($body !== null) {
        $headers[] = 'Content-Type: application/json';
    }
    $code = 0;
    if (function_exists('curl_init')) {
        $ch = curl_init($url);
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_CONNECTTIMEOUT => 4,
            CURLOPT_TIMEOUT => 8,
            CURLOPT_CUSTOMREQUEST => $method,
            CURLOPT_HTTPHEADER => $headers,
        ]);
        if ($body !== null) {
            curl_setopt($ch, CURLOPT_POSTFIELDS, $body);
        }
        $res = curl_exec($ch);
        $code = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
    } else {
        $ctx = stream_context_create(['http' => [
            'method' => $method,
            'header' => implode("\r\n", $headers),
            'content' => $body === null ? '' : $body,
            'timeout' => 8,
            'ignore_errors' => true,
        ]]);
        $res = false;
        $fp = @fopen($url, 'r', false, $ctx);
        if ($fp) {
            // The status line from the stream's own metadata, not the magic
            // $http_response_header, which PHP 8.5 deprecates.
            $meta = stream_get_meta_data($fp);
            $status = isset($meta['wrapper_data'][0]) ? $meta['wrapper_data'][0] : '';
            if (preg_match('/\s(\d{3})(\s|$)/', $status, $m)) {
                $code = (int) $m[1];
            }
            $res = stream_get_contents($fp);
            fclose($fp);
        }
    }
    if (!is_string($res) || $code < 200 || $code >= 300) {
        error_log('itlr reviews: HTTP ' . $code . ' from ' . $path . ': ' . substr((string) $res, 0, 300));
        return null;
    }
    $json = json_decode($res, true);
    return is_array($json) ? $json : null;
}

/** The configured place ID, the remembered one, or one looked up by name and address. */
function itlr_place_id($cfg, $dir)
{
    if ($cfg['place_id'] !== '') {
        return $cfg['place_id'];
    }
    $file = $dir . '/place-id.txt';
    if (is_file($file)) {
        $id = trim((string) file_get_contents($file));
        if ($id !== '') {
            return $id;
        }
    }
    $found = itlr_http('POST', '/places:searchText', $cfg['key'], 'places.id,places.displayName',
        json_encode(['textQuery' => ITLR_QUERY]));
    foreach ($found && isset($found['places']) && is_array($found['places']) ? $found['places'] : [] as $p) {
        $name = isset($p['displayName']['text']) ? $p['displayName']['text'] : '';
        // Only this business's own listing. A near miss would put another
        // company's reviews on this site, which is far worse than none.
        if (!empty($p['id']) && stripos($name, 'in the light roofing') !== false) {
            @file_put_contents($file, $p['id'], LOCK_EX);
            return $p['id'];
        }
    }
    error_log('itlr reviews: no "In The Light Roofing" listing found for ' . ITLR_QUERY);
    return null;
}

function itlr_fetch($cfg, $dir)
{
    $id = itlr_place_id($cfg, $dir);
    if (!$id) {
        return null;
    }
    $place = itlr_http('GET', '/places/' . rawurlencode($id) . '?languageCode=en', $cfg['key'],
        'id,rating,userRatingCount,googleMapsUri,reviews');
    if (!$place) {
        return null;
    }
    $reviews = [];
    foreach (isset($place['reviews']) && is_array($place['reviews']) ? $place['reviews'] : [] as $r) {
        $author = isset($r['authorAttribution']['displayName']) ? trim($r['authorAttribution']['displayName']) : '';
        $text = isset($r['text']['text']) ? $r['text']['text']
            : (isset($r['originalText']['text']) ? $r['originalText']['text'] : '');
        // A star rating with no words makes an empty card; it still counts in
        // the rating and the total, which come from Google directly.
        if ($author === '' || trim($text) === '') {
            continue;
        }
        $reviews[] = [
            'name' => $author,
            'profile' => isset($r['authorAttribution']['uri']) ? $r['authorAttribution']['uri'] : '',
            'rating' => isset($r['rating']) ? (int) $r['rating'] : 0,
            'text' => $text,
            'time' => isset($r['publishTime']) ? $r['publishTime'] : '',
            'ago' => isset($r['relativePublishTimeDescription']) ? $r['relativePublishTimeDescription'] : '',
        ];
    }
    usort($reviews, function ($a, $b) {
        return strcmp($b['time'], $a['time']);
    });
    return [
        'ok' => true,
        'placeId' => isset($place['id']) ? $place['id'] : $id,
        'rating' => isset($place['rating']) ? round((float) $place['rating'], 1) : null,
        'count' => isset($place['userRatingCount']) ? (int) $place['userRatingCount'] : null,
        'mapsUrl' => isset($place['googleMapsUri']) ? $place['googleMapsUri'] : '',
        'fetched' => gmdate('c'),
        'reviews' => $reviews,
    ];
}

$cfg = itlr_config();
if ($cfg['key'] === '') {
    itlr_out(['ok' => false, 'reason' => 'not-configured'], 300);
}
$dir = itlr_cache_dir();
if ($dir === null) {
    error_log('itlr reviews: no writable cache folder, so Google is not being called');
    itlr_out(['ok' => false, 'reason' => 'no-cache'], 300);
}

$cacheFile = $dir . '/reviews.json';
$failFile = $dir . '/last-failure';
$cached = null;
$age = PHP_INT_MAX;
if (is_file($cacheFile)) {
    $cached = json_decode((string) @file_get_contents($cacheFile), true);
    $age = time() - (int) @filemtime($cacheFile);
}
$usable = is_array($cached) && !empty($cached['ok']) && $age < ITLR_MAX_STALE;

if ($usable && $age < ITLR_TTL) {
    itlr_out($cached, 900);
}
if (is_file($failFile) && time() - (int) @filemtime($failFile) < ITLR_RETRY) {
    $usable ? itlr_out($cached, 300) : itlr_out(['ok' => false, 'reason' => 'unavailable'], 120);
}

// Stale or empty: one request refreshes, the rest are served what there is.
$lock = @fopen($dir . '/refresh.lock', 'c');
if (!$lock || !flock($lock, LOCK_EX | LOCK_NB)) {
    $usable ? itlr_out($cached, 60) : itlr_out(['ok' => false, 'reason' => 'refreshing'], 30);
}

$fresh = itlr_fetch($cfg, $dir);
if ($fresh) {
    $tmp = $cacheFile . '.' . getmypid();
    if (@file_put_contents($tmp, json_encode($fresh, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)) !== false) {
        @rename($tmp, $cacheFile);
    }
    @unlink($failFile);
    itlr_out($fresh, 900);
}
@touch($failFile);
$usable ? itlr_out($cached, 300) : itlr_out(['ok' => false, 'reason' => 'unavailable'], 120);
