<?php
/**
 * Form handler for the static publish of inthelightroofing.com.
 *
 * GENERATED by build/publish.mjs on every publish. Do not edit this file --
 * edit submitPhp() in build/publish.mjs and republish.
 *
 * Every form on the site posts here: build/seo/forms.mjs sets
 * action="/_forms/submit.php" on each one and drops the forminator_ajax class that
 * would otherwise send it to WordPress's admin-ajax, which does not exist on a
 * static host.
 */

// Never show a PHP notice to a visitor; the host's error log is where they go.
ini_set('display_errors', '0');
error_reporting(E_ALL);

// The business is in Allentown, PA, so the timestamp in the notification is
// written in the hours the person reading it keeps.
date_default_timezone_set('America/New_York');

$TO = 'info@inthelightroofing.com';
$FROM = 'In The Light Roofing website <info@inthelightroofing.com>';
$THANKS = '/thank-you/';

// A CV, not a video. The extensions are the ones the careers form itself names.
$MAX_UPLOAD = 8388608;
$ALLOWED_EXT = ['avif', 'heif', 'heics', 'heifs', 'pdf', 'docx', 'doc'];

// form id -> field name -> label and option text, harvested from the published
// pages at build time so the email calls every field what the visitor saw.
$FIELDS = ['2261' => ['name-1' => ['label' => 'Name'], 'phone-1' => ['label' => 'Phone'], 'email-1' => ['label' => 'Email'], 'select-1' => ['label' => 'How can we help you', 'options' => ['one' => 'Roof Repair', 'two' => 'Roof Replacement', 'New-Roof-Installment' => 'New Roof Installation', 'Roof-Inspections' => 'Roof Inspections', 'Insurance-Claim-Facilitation' => 'Insurance Claim Facilitation', 'Storm-Damage-Repair' => 'Storm Damage Repair']]], '4611' => ['name-1' => ['label' => 'Name'], 'phone-1' => ['label' => 'Phone'], 'email-1' => ['label' => 'Email'], 'textarea-1' => ['label' => 'How Can We Help']], '8072' => ['name-1' => ['label' => 'Name'], 'phone-1' => ['label' => 'Phone'], 'email-1' => ['label' => 'Email'], 'textarea-1' => ['label' => 'How Can We Help']], '8230' => ['name-1' => ['label' => 'Name'], 'phone-1' => ['label' => 'Phone'], 'email-1' => ['label' => 'Email'], 'textarea-1' => ['label' => 'More Details About You'], 'select-1' => ['label' => 'Job Positions', 'options' => ['one' => 'Project Manager', 'two' => 'Roof Repair Technician', 'New-Roof-Installment' => 'Outside Sales Representative', 'Roof-Inspections' => 'Inside Sales Representative']]], '9311' => ['name-1' => ['label' => 'Name'], 'phone-1' => ['label' => 'Phone'], 'email-1' => ['label' => 'Email'], 'textarea-1' => ['label' => 'How Can We Help']]];

// Posted with every form and never worth repeating in the email: Forminator's
// plumbing, and the hidden-N fields, which are baked into the mirror and so
// carry the capture machine's IP, the date of the capture and two unresolved
// merge tags rather than anything about this submission.
$MACHINE = ['forminator_nonce', '__referer', 'form_id', 'page_id', 'form_type',
  'current_url', 'render_id', 'action', 'referer_url', 'save_draft', 'form_uid',
  'MAX_FILE_SIZE', 'company_website', 'itlr_page'];

/**
 * A path on this site, or null. Everything that reaches a Location header goes
 * through here first: an absolute URL, a protocol-relative "//elsewhere" or a
 * header-splitting newline is refused outright rather than cleaned up, because
 * a redirector that tries to repair hostile input is how open redirects happen.
 */
function itlr_local_path($url) {
    if (!is_string($url) || $url === '') {
        return null;
    }
    $path = parse_url($url, PHP_URL_PATH);
    if (!is_string($path) || $path === '' || $path[0] !== '/' || substr($path, 0, 2) === '//') {
        return null;
    }
    if (preg_match('#[^A-Za-z0-9/_.~%:@!$&()*+,;=-]#', $path)) {
        return null;
    }
    return $path;
}

/**
 * The page the visitor was on. HTTP_REFERER is the only honest source: the
 * form's own current_url is Elementor's saved popup markup and names the wrong
 * page on more than a third of the instances. The itlr_page field
 * build/seo/forms.mjs stamps in is the fallback for the browsers and privacy
 * settings that send no referer at all.
 */
function itlr_page() {
    $host = isset($_SERVER['HTTP_HOST']) ? preg_replace('/:\d+$/', '', $_SERVER['HTTP_HOST']) : '';
    $ref = isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : '';
    if (is_string($ref) && $ref !== '') {
        $parts = parse_url($ref);
        $refHost = (is_array($parts) && isset($parts['host'])) ? $parts['host'] : '';
        if ($refHost === '' || ($host !== '' && strcasecmp($refHost, $host) === 0)) {
            $path = itlr_local_path($ref);
            if ($path !== null) {
                return $path;
            }
        }
    }
    // build/seo/forms.mjs stamps a bare path and nothing else, so a value that
    // carries a scheme or a host did not come from the markup and is not
    // trusted to name the page. Refused rather than reduced to its path: a
    // "//elsewhere.example/contact/" would otherwise pass as "/contact/".
    $raw = isset($_POST['itlr_page']) ? $_POST['itlr_page'] : '';
    if (is_string($raw) && $raw !== '' && $raw[0] === '/' && substr($raw, 0, 2) !== '//') {
        $stamped = itlr_local_path($raw);
        if ($stamped !== null) {
            return $stamped;
        }
    }
    return '/';
}

/** 303, so the browser turns the POST into a GET and a refresh cannot resubmit. */
function itlr_redirect($path) {
    header('Cache-Control: no-store');
    header('Location: ' . $path, true, 303);
    exit;
}

/** Back to the page the visitor was on, which shows nothing until someone styles ?form=error. */
function itlr_fail($page) {
    itlr_redirect($page . (strpos($page, '?') === false ? '?' : '&') . 'form=error');
}

/** Multi-line text with the control characters and the stray carriage returns taken out. */
function itlr_text($value) {
    if (!is_string($value)) {
        return '';
    }
    $value = str_replace(["\0", "\r\n", "\r"], ['', "\n", "\n"], $value);
    $value = preg_replace('/[\x01-\x08\x0B\x0C\x0E-\x1F\x7F]/', '', $value);
    return trim($value);
}

/** One line of text. Also what makes a value safe to put in a mail header. */
function itlr_line($value) {
    return trim(str_replace("\n", ' ', itlr_text($value)));
}

/** Cut to a byte length without splitting a UTF-8 character in half. */
function itlr_cut($value, $max) {
    if (strlen($value) <= $max) {
        return $value;
    }
    if (function_exists('mb_substr')) {
        return mb_substr($value, 0, $max, 'UTF-8');
    }
    return preg_replace('/[\x80-\xBF]*$/', '', substr($value, 0, $max));
}

/* ------------------------------------------------------------------------ */

if (!isset($_SERVER['REQUEST_METHOD']) || strtoupper($_SERVER['REQUEST_METHOD']) !== 'POST') {
    http_response_code(405);
    header('Allow: POST');
    header('Content-Type: text/plain; charset=UTF-8');
    echo "This address accepts form submissions only.\n";
    exit;
}

$page = itlr_page();

// A post larger than the host's post_max_size arrives with $_POST and $_FILES
// emptied and no warning of its own. Say so here rather than letting it fall
// through and look like an empty form.
if (empty($_POST) && isset($_SERVER['CONTENT_LENGTH']) && (int) $_SERVER['CONTENT_LENGTH'] > 0) {
    itlr_fail($page);
}

// The bot trap, before any validation. A filled-in honeypot gets the same
// answer a real submission gets, so nothing is learned from the difference.
if (itlr_line(isset($_POST['company_website']) ? $_POST['company_website'] : '') !== '') {
    itlr_redirect($THANKS);
}

$name = itlr_cut(itlr_line(isset($_POST['name-1']) ? $_POST['name-1'] : ''), 200);
$phone = itlr_cut(itlr_line(isset($_POST['phone-1']) ? $_POST['phone-1'] : ''), 200);
$email = itlr_cut(itlr_line(isset($_POST['email-1']) ? $_POST['email-1'] : ''), 250);

// A name and one way to answer. Nothing else on any of the five forms is worth
// turning a person away over.
if ($name === '') {
    itlr_fail($page);
}
if ($email !== '' && !filter_var($email, FILTER_VALIDATE_EMAIL)) {
    itlr_fail($page);
}
if ($phone === '' && $email === '') {
    itlr_fail($page);
}

$formId = preg_replace('/[^0-9]/', '', itlr_line(isset($_POST['form_id']) ? $_POST['form_id'] : ''));
$known = isset($FIELDS[$formId]) ? $FIELDS[$formId] : [];

// The form's own name for itself, for the subject line. It arrives from the
// client like everything else, so it is cut back to a short label.
$formName = preg_replace('/[^A-Za-z0-9 &\/\'-]/', '', itlr_line(isset($_POST['hidden-4']) ? $_POST['hidden-4'] : ''));
$formName = trim(preg_replace('/\s+/', ' ', $formName));
if ($formName === '') {
    $formName = 'Website form';
}
$formName = substr($formName, 0, 40);

/* ---------------------------------------------------------------- the body */

$inline = [];
$blocks = [];
$seen = [];

// The form's own fields first, in the order they appear on the page, labelled
// the way the page labels them and with a dropdown's visible text in place of
// the value it posts -- the careers dropdown sends "Roof-Inspections" for
// "Inside Sales Representative".
foreach ($known as $field => $meta) {
    $seen[$field] = true;
    if (!isset($_POST[$field]) || !is_string($_POST[$field])) {
        continue;
    }
    $value = itlr_cut(itlr_text($_POST[$field]), 20000);
    if ($value === '') {
        continue;
    }
    if (isset($meta['options']) && isset($meta['options'][$value])) {
        $value = $meta['options'][$value];
    }
    $label = (isset($meta['label']) && $meta['label'] !== '') ? $meta['label'] : $field;
    if (strpos($value, "\n") === false) {
        $inline[] = [$label, $value];
    } else {
        $blocks[] = [$label, $value];
    }
}

// Anything else a form grows later still reaches the inbox, under its own name.
foreach ($_POST as $field => $value) {
    if (isset($seen[$field]) || !is_string($field) || !is_string($value)) {
        continue;
    }
    // apbct_* and ct_* are CleanTalk's, added to the form by its own script as
    // the visitor types. One of them is a five-kilobyte base64 blob of
    // telemetry for a service that has no server side here.
    if (in_array($field, $MACHINE, true) || strpos($field, 'hidden-') === 0
        || strpos($field, 'apbct') === 0 || strpos($field, 'ct_') === 0) {
        continue;
    }
    $value = itlr_cut(itlr_text($value), 20000);
    if ($value === '') {
        continue;
    }
    if (strpos($value, "\n") === false) {
        $inline[] = [$field, $value];
    } else {
        $blocks[] = [$field, $value];
    }
}

/* ---------------------------------------------------------- the attachment */

$attachment = null;
if (isset($_FILES['upload-1']) && is_array($_FILES['upload-1'])
    && isset($_FILES['upload-1']['error']) && !is_array($_FILES['upload-1']['error'])
    && (int) $_FILES['upload-1']['error'] !== UPLOAD_ERR_NO_FILE) {
    $file = $_FILES['upload-1'];
    if ((int) $file['error'] !== UPLOAD_ERR_OK || !is_uploaded_file($file['tmp_name'])) {
        itlr_fail($page);
    }
    $size = (int) $file['size'];
    if ($size <= 0 || $size > $MAX_UPLOAD) {
        itlr_fail($page);
    }
    // The client filename is used for one thing only, its extension, and even
    // that is taken after the path separators are stripped out of it. The name
    // the attachment is sent under is built here.
    $client = str_replace('\\', '/', (string) $file['name']);
    $ext = strtolower(pathinfo(basename($client), PATHINFO_EXTENSION));
    if (!in_array($ext, $ALLOWED_EXT, true)) {
        itlr_fail($page);
    }
    $bytes = file_get_contents($file['tmp_name']);
    if ($bytes === false || strlen($bytes) === 0) {
        itlr_fail($page);
    }
    $slug = trim(strtolower(preg_replace('/[^A-Za-z0-9]+/', '-', $name)), '-');
    if ($slug === '') {
        $slug = 'attachment';
    }
    $attachment = ['name' => substr($slug, 0, 40) . '-' . date('Ymd-His') . '.' . $ext, 'bytes' => $bytes];
}

/* ---------------------------------------------------------------- the mail */

$width = 0;
foreach ($inline as $row) {
    $width = max($width, strlen($row[0]));
}
$width = max($width, 9);

$body = 'New ' . $formName . ' submission from ' . $page . "\n\n";
foreach ($inline as $row) {
    $body .= str_pad($row[0] . ':', $width + 2) . $row[1] . "\n";
}
foreach ($blocks as $row) {
    $body .= "\n" . $row[0] . "\n" . str_repeat('-', strlen($row[0])) . "\n" . $row[1] . "\n";
}
if ($attachment !== null) {
    $body .= "\n" . 'Attached: ' . $attachment['name'] . "\n";
}
$body .= "\n" . str_repeat('-', 40) . "\n";
$body .= str_pad('Page:', $width + 2) . $page . "\n";
$body .= str_pad('Received:', $width + 2) . date('Y-m-d H:i:s T') . "\n";
if (isset($_SERVER['REMOTE_ADDR'])) {
    $body .= str_pad('From IP:', $width + 2) . itlr_line($_SERVER['REMOTE_ADDR']) . "\n";
}

$subject = itlr_line('In The Light Roofing: ' . $formName . ' from ' . $page);

$boundary = 'itlr-' . (function_exists('random_bytes') ? bin2hex(random_bytes(12)) : md5(uniqid('', true)));

$headers = ['From: ' . $FROM];
if ($email !== '') {
    // So hitting reply answers the person who filled the form in.
    $headers[] = 'Reply-To: ' . itlr_line($email);
}
$headers[] = 'MIME-Version: 1.0';

if ($attachment === null) {
    $headers[] = 'Content-Type: text/plain; charset=UTF-8';
    $headers[] = 'Content-Transfer-Encoding: base64';
    // base64 rather than 8bit: it is the only encoding that cannot be tripped
    // up by a long line or a mail server that rewrites one.
    $message = chunk_split(base64_encode($body), 76, "\r\n");
} else {
    $headers[] = 'Content-Type: multipart/mixed; boundary="' . $boundary . '"';
    $message = '--' . $boundary . "\r\n"
        . "Content-Type: text/plain; charset=UTF-8\r\n"
        . "Content-Transfer-Encoding: base64\r\n\r\n"
        . chunk_split(base64_encode($body), 76, "\r\n") . "\r\n"
        . '--' . $boundary . "\r\n"
        . 'Content-Type: application/octet-stream; name="' . $attachment['name'] . "\"\r\n"
        . "Content-Transfer-Encoding: base64\r\n"
        . 'Content-Disposition: attachment; filename="' . $attachment['name'] . "\"\r\n\r\n"
        . chunk_split(base64_encode($attachment['bytes']), 76, "\r\n") . "\r\n"
        . '--' . $boundary . "--\r\n";
}

if (!mail($TO, $subject, $message, implode("\r\n", $headers))) {
    itlr_fail($page);
}

itlr_redirect($THANKS);
